full_rebuild: true
name: Gridster
description: the material experience for jekyll
domain: #If you want to force HTTPS, put down the domain without the http: e.g. example.com
url: #place url
baseurl: /gridster-jekyll-theme #place folder name if site is served in subfolder
author: #For jekyll-feed
  name: temp
  email: temp@rary.com
  uri: https://temp.github.com
permalink: /:categories/:title/
paginate: 8
paginate_path: /page/:num/
infinite_scroll: true #change to false if you want to use pagination
sidebar_toc: true #true if you want the collapsible TOC appears in the sidebar
tag_dir: /tag
tags_dir: /tags #All tags summary page
category_dir: /category
categories_dir: /categories  #All categories summary page
author_dir: /author
author_title_prefix: 'Posted by '
authors_dir: /about #ALl authors summary page, a.k.a. about
changefreq: always
media_folder: /media
author_default_avatar: /profile-pic.jpg
tumblr: "#"
pinterest: "#"
instagram: "#"
twitter: "#"
facebook: "#"
youtube: "#"
vimeo: "#"
soundcloud: "#"
email: "#"
rss: feed.xml #For nav. The path is fixed by jekyll-feed; omitting this will result in no icon in nav.

encoding: utf-8
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      sidebar: true #true for sidebar false for none
      sidebar_type: "material" #"material" or "classic"
      sidebar_position: "left" #"left" or "right"
      type: "standard"
      homedisplay: "featimg"
      comments: false
kramdown:
  input: GFM
  hard_wrap: false
exclude: [.git, .gitignore, sass, .sass-cache, package.json, gruntfile.js, node_modules, README.md, jekyllbuild, Gemfile, Gemfile.lock, preview, img, LICENCE, Organizational Overview.*]
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  layouts:
    category: category_index
    tag: tag_index
    year: archive_index
  permalinks:
    category: '/category/:name/' #should be in tag_dir
    tag: '/tag/:name/'  #should be in category_dir
    year: '/archive/:year/'

sass:
  style: compressed

compress_html:
  clippings: all
  comments: []
  endings: []
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]

# prose.io configurations
prose:
  media: "img"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "select"
          label: "Layout"
          help: "display post at full width or with sidebar"
          options:
            - name: "with sidebar"
              value: "post"
            - name: "full width"
              value: "post-full"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          help: "author id as defined within _data/authors.yml"
          type: "text"
      - name: "featimg"
        field:
          element: "text"
          label: "Featured Image"
          help: "featured image within the img-folder"
          type: "text"
      - name: "type"
        field:
          element: "select"
          label: "Post Type"
          help: "each type has some special feature"
          options:
            - name: "Standard"
              value: "standard"
            - name: "Image"
              value: "image"
            - name: "Gallery"
              value: "gallery"
            - name: "Audio"
              value: "audio"
            - name: "YouTube"
              value: "youtube"
            - name: "Vimeo"
              value: "vimeo"
      - name: "homedisplay"
        field:
          element: "select"
          label: "Home Display"
          help: "decide whether to display embedded element (for post types: audio, youtube, vimeo) or Featured Image on home page"
          options:
            - name: "Featured Image"
              value: "featimg"
            - name: "Embedded Element"
              value: "iframe"
      - name: "vimeo-embed"
        field:
          element: "text"
          label: "Vimeo Embedding Code"
          help: "Set post type to vimeo in order for this to work"
      - name: "gallery-id"
        field:
          element: "text"
          label: "Gallery ID"
          help: "ID of the gallery defined within _data/galleries.yml - use include in content to use"
      - name: "audio-embed"
        field:
          element: "text"
          label: "Audio Embedding Code"
          help: "Set post type to audio in order for this to work"
      - name: "yt-video-id"
        field:
          element: "text"
          label: "YouTube Video ID"
          help: "Set post type to youtube in order for this to work. Do not set featured image, as the youtube video thumbnail will be used"
          type: "text"